### ISSUE TITLE
AttributeError: 'NotionAI' object has no attribute 'write_with_topic'.

### ISSUE THREAD

**Issue by 19thchance** [Vaayne/NotionAI-Plus#1]
Hello, I installed the package and write the code below that is exactly same as your example code.
```py
import os
from notionai import NotionAI

TOKEN = os.getenv("NOTION_TOKEN")

def main():
    ai = NotionAI(TOKEN)
    res = ai.blog_post("write a blog about the meaning of life")
    print(res)

if __name__ == "__main__":
    main()
```

I inputed my token correctly in the `.env` file, but I got an error:
```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    main()
  File "main.py", line 8, in main
    res = ai.blog_post("write a blog about the meaning of life")
  File "/home/runner/PositiveNegligibleLifecycles/venv/lib/python3.10/site-packages/notionai/notionai.py", line 239, in blog_post
    return self.write_with_topic(TopicEnum.blog_ost, prompt)
AttributeError: 'NotionAI' object has no attribute 'write_with_topic'. Did you mean: 'writing_with_topic'?
```

Hope you have a nice day 🙂

**Comment by vaayne** [comment]
@unsignd  Hi, sorry for the inconvenience. Please update to the latest version using `pip install --upgrade notionai-py` and try again.

**Comment by 19thchance** [comment]
Successfully be runned now!
Thank you.
